@extends('project.layouts.module.form.template')
<?php
/**
 * @var \App\Module $module
 * @var \App\User $user
 * @var string $formState create|edit
 * @var array $formConfig
 * @var string $uuid Only available during creation
 * @var bool $editable
 * @var array $immutables
 * @var \App\District $element
 * @var \App\District $district
 * @var \App\Tenant $tenant
 * @var \App\Project\Modules\Districts\DistrictViewProcessor $view
 */
$district = $element;
?>
@section('content-top')
    @parent
    @include('mainframe.form.back-link',['var'=>['element'=>$element->division]])
@endsection

@section('content')
    <div class="row">
        <div class="col-md-11 col-lg-9 col-xl-8">
            @if($formState == 'create')
                {{ Form::open($formConfig) }} <input name="uuid" type="hidden" value="{{$uuid}}"/>
            @elseif($formState == 'edit')
                {{ Form::model($element, $formConfig)}}
            @endif

            {{---------------|  Form input start |-----------------------}}
            @include('form.select-model',['var'=>['name'=>'division_id','label'=>'Division','model'=>\App\Division::class]])
            <div class="clearfix"></div>
            @include('form.text',['var'=>['name'=>'name','label'=>'Name']])
            @include('form.text',['var'=>['name'=>'name_bn','label'=>'Name (Bangla)']])
            @include('form.number',['var'=>['name'=>'code','label'=>'Code']])
            @include('form.plain-text',['var'=>['name'=>'combined_code','label'=>'Combined Code','tooltip'=>'This code is auto generated by the system.']])
            @include('form.number',['var'=>['name'=>'longitude','label'=>'Longitude','params'=>['step'=>'any']]])
            @include('form.number',['var'=>['name'=>'latitude','label'=>'Latitude','params'=>['step'=>'any']]])

            <div class="clearfix"></div>
            @include('form.is-active')
            <div class="clearfix"></div>

            @if($element->isCreated())
                <div class="col-md-9 no-padding-l" style="margin-bottom: 10px;">
                    <h3>Upazilas</h3>
                    @if(user()->can('update',$element))
                        <?php
                        /*
                        |--------------------------------------------------------------------------
                        | Dynamic modal content from partial
                        |--------------------------------------------------------------------------
                        */
                        $var = [
                            'name' => 'createUpazilaModal',
                            'btn_text' => "<ion-icon name='add-outline'></ion-icon> Add Upazila",
                            'btn_class' => 'btn-bordered-blue',
                            'url' => route('partials.upazila-add-modal',
                                ['district_id' => $element->id]),
                        ];
                        ?>
                        @include('mainframe.layouts.default.includes.modals.dynamic')
                    @endif

                    <?php
                    $datatable = new \App\Project\Datatables\UpazilaWidgetDatatable();
                    $datatable->addUrlParam(['district_id' => $element->id]);
                    $datatable->bPaginate = true;
                    //$datatable->minimal();
                    ?>
                    @include('form.datatable',['datatable'=>$datatable])
                    <div class="clearfix"></div>
                </div>
            @endif

            <div class="clearfix"></div>
            @include('form.action-buttons')
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('js')
    @parent
    @include('project.modules.districts.form.js')
@endsection
