<?php

namespace Tests\Feature\Mainframe\Auth;

use Mail;
use App\User;
use Notification;
use Tests\TestCase;
use App\Project\Notifications\Auth\VerifyEmail;

class UserRegistrationTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Guest can see registration page
     *
     * @return void
     */
    public function test_see_registration_page()
    {
        $this->get('register')
            ->assertStatus(200)
            ->assertSee('User Registration')->assertSeeInOrder([
                'Email',
                'Password',
                'Confirm Password',
                'Register',
            ]);
    }

    /**
     * @return void
     */
    public function test_guest_can_register_to_default_user_group()
    {
        Mail::fake();
        Notification::fake();

        $firstName = $this->faker->firstName;
        $email = $this->faker->email;

        $this->followingRedirects()
            ->post('register', [
                'first_name' => $firstName,
                'last_name' => $this->faker->lastName,
                'email' => $email,
                'password' => $this->password,
                'password_confirmation' => $this->password,
                // 'group_ids' => [Group::byName('user')->id], // Note: If no group is specified then by default 'user' group will be selected
            ])
            ->assertStatus(200)
            ->assertSee("A verification link has been sent to your email address. Click the link and login with your username and password to complete the verification.");

        $user = User::where('email', $email)->first(); // Get this newly created user from database

        Notification::assertSentTo([$user], VerifyEmail::class); // This is a mailable class

        $this->assertDatabaseHas('users', [
            'id' => $user->id,
            'email_verified_at' => null,
            'group_ids' => "[\"".User::USER_GROUP_ID."\"]",
        ]);

        echo "User #{$user->id} : {$user->email} created";

        $this->followingRedirects()
            ->post('login', [
                'email' => $user->email,
                'password' => $this->password,
            ])
            ->assertStatus(200)
            ->assertSee("Before proceeding, please check your email for a verification link.");


        $this->followingRedirects()
            ->post('email/resend')
            ->assertStatus(200)
            ->assertSee('Email verification required')
            ->assertDontSee("Resend verification link");

        Notification::assertSentTo([$user], VerifyEmail::class);
    }


    public function test_guest_cannot_see_resend_verification_code_page()
    {
        $this->withExceptionHandling();
        // Guest is redirected to login
        $this->get('email/verify')->assertRedirect('login');

    }


    public function test_verified_user_can_see_dashboard_upon_login()
    {

        $user = $this->newlyRegisteredUser();
        $user->update(['email_verified_at' => now()]); // Force verify
        $this->be($user);
        $this->followingRedirects()->get('email/verify')->assertSee('Dashboard');

    }

    public function test_verified_user_can_login_and_see_dashboard()
    {
        $user = $this->newlyRegisteredUser(); // Get this newly created user from database

        $this->followingRedirects()
            ->post('login', [
                'email' => $user->email,
                'password' => $this->password,
            ])
            ->assertStatus(200)
            ->assertSee('Dashboard');
    }

    public function test_user_can_access_data_block_variable()
    {
        $user = $this->newlyRegisteredUser(); // Get this newly created user from database

        $this->be($user);
        $this->followingRedirects()
            ->get('/')
            ->assertStatus(200)
            ->assertViewHas('sampleData', [
                'books' => [
                    'purchased' => 10,
                    'read' => 7,
                ],
            ]);
    }

    /*
    |--------------------------------------------------------------------------
    | Helpers
    |--------------------------------------------------------------------------
    */

    /**
     * @return User
     */
    public function newlyRegisteredUser()
    {
        return $this->latestUser();
    }

}
