@extends('mainframe.layouts.blank.partial')

<?php
/**
 * @var \App\Division $division
 * @var string $uuid
 */
?>

@section('content')
    <div class="modal-header">
        <h3 class="modal-title uppercase" id="modalLabel">Add District</h3>
        <button id="districtAddModalCloseButton" type="button" class="close"
                data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <form id="districtAddForm" name="districtAddForm" action="{{route('districts.store')}}" method="POST">
        <div class="modal-body">
            <div class="row">
                @csrf
                <input name="division_id" type="hidden" value="{{$division->id}}">
                <input name="uuid" type="hidden" value="{{$uuid}}">
                <div class="col-md-12">
                    @include('form.text',['var'=>['name'=>'name','label'=>'Name']])
                    @include('form.text',['var'=>['name'=>'name_bn','label'=>'Name (Bangla)']])
                    @include('form.number',['var'=>['name'=>'code','label'=>'Code']])
                    @include('form.plain-text',['var'=>['name'=>'combined_code','label'=>'Combined Code','tooltip'=>'This code is auto generated by the system.']])
                    @include('form.number',['var'=>['name'=>'longitude','label'=>'Longitude','params'=>['step'=>'any']]])
                    @include('form.number',['var'=>['name'=>'latitude','label'=>'Latitude','params'=>['step'=>'any']]])
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="modal-footer">
            <button id="districtAddFormButton" name="districtAddFormButton"
                    type="submit" class="btn btn-primary">Save
            </button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </form>
@endsection

@section('js')
    @parent
    <script type="text/javascript">
        /**************************
         * 1 - Add FE validations
         *************************/

        $('#districtAddForm #name').addClass('validate[required]');
        $('#districtAddForm #code').addClass('validate[required]');
        $('#districtAddForm #name_bn').addClass('validate[required]');
        $('#districtAddForm #longitude').addClass('validate[number]');
        $('#districtAddForm #latitude').addClass('validate[number]');

        /************************************************************
         * 2 - Handle form post using mainframe default form function
         ************************************************************/
        enableAjaxFormSubmission('districtAddForm',
            function success(response) {
                $("#createDistrictModal").modal('hide');               // Hide the dynamic modal
                $('#districtDatatable').DataTable().ajax.reload(); // Reload datatable
            },
            function fail(response) {
                // console.log(response);                               // Log response (Debug)
                showResponseModal(response);                            // Show the default response modal
            }
        );

    </script>
@endsection
